const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';

const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
const BOOK_DELETED_FROM_CART = 'BOOK_DELETED_FROM_CART';

const FILTERED_BOOKS_PRICE = 'FILTERED_BOOKS_PRICE';


export {
    FETCH_BOOKS_REQUEST,
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_FAILURE,

    BOOK_ADDED_TO_CART,
    BOOK_DELETED_FROM_CART,
    FILTERED_BOOKS_PRICE
}